name: flutter_image_map_example
version: 0.1.0
description: Little demo
dependencies:
  flutter:
    sdk: flutter
  flutter_image_map:
environment:
  sdk: '>=2.2.0 <3.0.0'
flutter:
  uses-material-design: true
  assets:
    - assets/